name: Build

on:
  push:
    branches:
      - sample
      - master

jobs:
  test:
    name: Build app
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Delete modules cache
        run: rm -f ~/.gradle/caches/modules-2/modules-2.lock

      - name: Delete plugin resolution cache
        run: rm -fr ~/.gradle/caches/*/plugin-resolution/

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.android/build-cache
            ~/.m2
            ~/.gradle
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Delete previous outputs
        run: rm -rf ./app/build/outputs

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Make gradle wrapper executable
        run: chmod +x gradle/wrapper/gradle-wrapper.jar

      - name: Build
        run: ./gradlew clean test --full-stacktrace
