name: Build

on:
  push:
    branches:
      - sample
      - master

jobs:
  test:
    name: Test build
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Delete modules cache
        run: rm -f ~/.gradle/caches/modules-2/modules-2.lock

      - name: Delete plugin resolution cache
        run: rm -fr ~/.gradle/caches/*/plugin-resolution/

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.android/build-cache
            ~/.m2
            ~/.gradle
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Delete previous outputs
        run: rm -rf $TRAVIS_BUILD_DIR/app/build/outputs

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Make gradle wrapper executable
        run: chmod +x gradle/wrapper/gradle-wrapper.jar

      - name: Build
        run: ./gradlew clean test --full-stacktrace

      - name: Build master app
        run: ./gradlew clean :app:assembleRelease --full-stacktrace;

      - name: Build master library
        run: ./gradlew clean :library:assembleRelease --full-stacktrace;

      - name: Publish apk
        env:
          GITHUB_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: chmod +x ./publish_apk.sh; ./publish_apk.sh
